---
- name: Install Docker & python2-pip-8.1.2 & pip install Docker
  hosts: ansible-target1
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
    - name: Enable docker
      service:
        name: docker
        enabled: yes
        state: started
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
    - name: Install python2-pip
      yum:
        name: python2-pip-8.1.2-10.el7.noarch
        state: present
    - name: Pip install Docker
      pip:
        name: docker
    - name: create a network   #docker network
      docker_network:
        name: proxy_net
        ipam_config:
        - subnet: 172.19.1.0/24
          gateway: 172.19.1.2
          iprange: 172.19.1.0/26
    - name: copy the site directory in place
      copy:
        src: nginx.conf
        dest: /tmp/nginx.conf
    - name: Install httpd container
      docker_container:
        name: httpd
        image: httpd:latest
        detach: true
        state: started
        restart: yes
        hostname: server1
        restart_policy: always
        ports:
          - 8181:80
        networks:
           - name: proxy_net
             ipv4_address: "172.19.1.3"
    - name: Install nginx container
      docker_container:
        name: nginx
        image:  nginx:latest
        detach: true
        state: started
        restart: yes
        hostname: server2
      #  network_mode: "{{ docker_network }}"
        restart_policy: always
        ports:
          - 8080:80
        networks:
           - name: proxy_net
             ipv4_address: "172.19.1.4"
        volumes:
         - /tmp/nginx.conf:/etc/nginx/nginx.conf
